In [1]:
import pandas as pd
import requests
import json

In [2]:
g_perth_sa2 = pd.read_csv("SA2_2016_AUST.csv")
g_perth_sa2.head()

,SA2_MAINCODE_2016,SA2_5DIGITCODE_2016,SA2_NAME_2016,SA3_CODE_2016,SA3_NAME_2016,SA4_CODE_2016,SA4_NAME_2016,GCCSA_CODE_2016,GCCSA_NAME_2016,STATE_CODE_2016,STATE_NAME_2016,AREA_ALBERS_SQKM
0,101021007,11007,Braidwood,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,3418.3525
1,101021008,11008,Karabar,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,6.9825
2,101021009,11009,Queanbeyan,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,4.7634
3,101021010,11010,Queanbeyan - East,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,13.0034
4,101021011,11011,Queanbeyan Region,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,3054.4099

In [3]:
g_perth_sa2 = g_perth_sa2.loc[g_perth_sa2["GCCSA_NAME_2016"] == "Greater Perth"]
g_perth_cols = ["SA2_MAINCODE_2016", "SA2_NAME_2016","GCCSA_NAME_2016"]
g_perth_sa2= g_perth_sa2[g_perth_cols].copy()
g_perth_sa2.dtypes
g_perth_sa2["SA2_MAINCODE_2016"] = g_perth_sa2["SA2_MAINCODE_2016"].apply(str)

In [4]:
#make a list of SA2 Maincode for ABS API
sa2_list = g_perth_sa2["SA2_MAINCODE_2016"].tolist()
income_dict = {"SA2 Code" : [], "SA2 Name":[], "Income":[], "2006":[],"2011":[]}
income_dict_2016 = {"SA2 Code" : [], "SA2 Name":[], "Income":[], "2016":[]}

In [5]:
# Income 
income_url = 'http://stat.data.abs.gov.au/sdmx-json/data/ABS_CENSUS2011_T24/TOT.04.5.SA2.505031108.A/all?detail=Full&dimensionAtObservation=AllDimensions&startPeriod=2006&endPeriod=2011'

bins_income = ['03','04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14_17']

    
for sa2 in sa2_list:
    for bins in bins_income:
        try:
             response = requests.get(f"http://stat.data.abs.gov.au/sdmx-json/data/ABS_CENSUS2011_T24/TOT.{bins}.5.SA2.{sa2}.A/all?detail=Full&dimensionAtObservation=AllDimensions&startPeriod=2006&endPeriod=2011")
             income = response.json()
#              print(income)
             income_dict["SA2 Code"].append(income["structure"]["dimensions"]["observation"][4]["values"][0]["id"])
             income_dict["SA2 Name"].append(income["structure"]["dimensions"]["observation"][4]["values"][0]["name"])
             income_dict["Income"].append(income["structure"]["dimensions"]["observation"][1]["values"][0]["name"])
             income_dict["2006"].append(income["dataSets"][0]["observations"]["0:0:0:0:0:0:0"][0])
             income_dict["2011"].append(income["dataSets"][0]["observations"]["0:0:0:0:0:0:1"][0])
        except:
            print("error at sa2 bin")

error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin
error at sa2 bin

In [6]:
income_df = pd.DataFrame(income_dict)
print(income_df)

       SA2 Code              SA2 Name          Income  2006   2011
0     502011021  Dawesville - Bouvard         $1-$199   3.0    9.0
1     502011021  Dawesville - Bouvard       $200-$299  13.0   23.0
2     502011021  Dawesville - Bouvard       $300-$399  16.0   46.0
3     502011021  Dawesville - Bouvard       $400-$599  27.0   56.0
4     502011021  Dawesville - Bouvard       $600-$799  23.0   53.0
...         ...                   ...             ...   ...    ...
1987  507051193               Warnbro   $1,250-$1,499  98.0  119.0
1988  507051193               Warnbro   $1,500-$1,999  80.0  151.0
1989  507051193               Warnbro   $2,000-$2,499  41.0   68.0
1990  507051193               Warnbro   $2,500-$2,999  18.0   37.0
1991  507051193               Warnbro  $3,000 or more  17.0   49.0

[1992 rows x 5 columns]

In [10]:
income_df.to_csv("income2006_2011.csv")

In [7]:
# # Income 2016
# income_2016_url = 'http://stat.data.abs.gov.au/sdmx-json/data/ABS_C16_T21_SA/TOT.07.5.SA2.505021092/all?detail=Full&dimensionAtObservation=AllDimensions&startPeriod=2016&endPeriod=2016'

# bins_income_2016 = ['03','04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14','15', '16', '17', '18', '19', '20', '21', '22']
    
# for sa2 in sa2_list:
#     for bins in bins_income_2016:
#              response = requests.get(f"http://stat.data.abs.gov.au/sdmx-json/data/ABS_C16_T21_SA/TOT.{bins}.5.SA2.{sa2}/all?detail=Full&dimensionAtObservation=AllDimensions&startPeriod=2016&endPeriod=2016")
#              income_2016 = response.json()
#              income_dict_2016["SA2 Code"].append(income_2016["structure"]["dimensions"]["observation"][4]["values"][0]["id"])
#              income_dict_2016["SA2 Name"].append(income_2016["structure"]["dimensions"]["observation"][4]["values"][0]["name"])
#              income_dict_2016["Income"].append(income_2016["structure"]["dimensions"]["observation"][1]["values"][0]["name"])
#              income_dict_2016["2016"].append(income_2016["dataSets"][0]["observations"]["0:0:0:0:0:0"][0])

In [8]:
# income_df_2016 = pd.DataFrame(income_dict_2016)
# print(income_df_2016)

In [9]:
# income_df_2016.to_csv('Income 2016.csv')